<a href="https://colab.research.google.com/github/acfa2-bit/ETL_Uni/blob/main/VD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# criando uma lista Python

minhalista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhalista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
#Transformando essa lista em uma Array NumPy
#O array é multidimensional

meuarray = np.array(minhalista)
meuarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# Formas simplificadas de criar arrays
# Uma forma mais simples de criarmos uma lista:
minhalista = list (range(9))
minhalista

#Transformando agora essa lista em um Array Numpy
array1 = np.array(range(9))
array1

#Arange: Fazendo as etaás anteriores numa unica sintaxe:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#Start, stop, step:
array3 = np.arange(0, 10, 0.5)
array3

#Arredondando os valores obtidos
novoarray = np.around(array3)
novoarray

#Também podemos "forçar" o tipo dos elementos:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#Também podemos pré-determinar o tipo dos elementos
array4 = np.arange(12)

#Ainda teremos os números inteiros, mas posso deixar meu array previamente preparado para trabalhar futuramento com os tipos float (.)
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
#Verificando o tipo do objeto (estrutura de dados):
type(array4)

#Verificando o tipo dos elementos internos do array
array4.dtype

dtype('float64')

In [12]:
#Criação e seleção de elementos

#Também podemos criar um array digitando os valores
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

#Seleção e fatiamento
#Selecionando um elemento específico
vetor1[3]

#Selecionando um intervalo específico
vetor1[0:2] #ou também print(vetor1[0:2])

#Selecionando um intervalo específico com saltos
#vetor1[1::2]

[0 1 2 3 4]


array([0, 1])

In [13]:
#Criando um array de strings:
s = np.array(['Python', 'Profissional', 'Java', 'Água'])
s

#Misturando tipos (strings e números):
s = np.array(['Python', 1464322315, 'Profissional', 'Java', 'Água'])
s

array(['Python', '1464322315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [16]:
#Alteração de elementos e restrição de tipos

#Alterando um elemento array:
vetor1[2] = 10
vetor1

#Vamos tentar incluir elementos de outro tipo (string):
vetor1[0] = "novo elemento"
vetor1

#Agora tente o seguinte (float em array int):
vetor1[0] = 45.6
vetor1

ValueError: invalid literal for int() with base 10: 'novo elemento'

In [18]:
#Linspace e Matrizes
#importante para Machine Learning, Deep Learning.

arr1 = np.arange(10) # 0 a 9 (stop)
arr2 = np.arange(10, 20) # 10 a 19 (start, stop)
arr3 = np.arange(10, 20, 2) # 10 a 19 (start, stop, step)
arr4 = np.arange(10, 20, 1.4) #passo float




In [24]:
# Exemplos de linspace

arr5=np.linspace(10,20,11)

arr6=np.linspace(10,20,101)

arr7=np.linspace(0, np.pi, 100)

arr5
arr6
arr7


array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [25]:
#Criando a primeira matriz

#Criando a primeira matriz (com quebra de linha para melhor leitura):
minhamatriz = np.array([[1, 2, 3],
                        [4, 5, 6]])
minhamatriz

#Lembrando que voce pode escrever apenas assim (na mesma linha):
minhamatriz = np.array([[1,2,3], [4, 5,6]])
minhamatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Podemos criar uma matriz a partir de uma lista de listas:
minhalista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

# Agora usaremos a função np.matrix:
minhamatriz = np.matrix(minhalista)
minhamatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [29]:
# A função np.zeros pode formar tanto valores quanto matrizes preenchidos com zeros
# Vetor 1D
x = np.zeros(3)
x

#Matriz (2D)
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
# Você não precia necessariamente criar uma variável para usar a função
# mas, para armazenar e usarmos depois, temos que criar a variável, para guardarmos nela
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# A função np.ones funciona da mesma forma que a np.zeros:
x = np.ones((4,4))
x

# Para preencher apenas com 8s (ou com qualquer outro número que não 0 e 1 - multiplicamos pelo do one)
x = 8*np.ones((4,4))
x



array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [38]:
#Matrizes diagonais e identidade

#Matrizes com valores na diagonal:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

# Matriz identidade (diagonal principal com 1, resto 0):
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
#Verficando o chape da matriz
#Podemos verificar o shape (formato) da matriz, que nos retorna uma tupla com o número de linhas e colunas

np.shape(minhamatriz)

(3, 3)

In [40]:
#Verificando tipos

#tipo do objeto como um todo
type(minhamatriz)

#Verificando o tipo dos dados da matriz - tipo do conteúdo
minhamatriz.dtype

dtype('int64')

In [41]:
# Seleção e alteração de elementos

#Selecionando elementos da matriz:
minhamatriz[2,1] #linha indice 2, coluna indice 1

#Alterando um elemento da matriz:
minhamatriz[2,1] = 100
minhamatriz

matrix([[ 13,  81,  22],
        [  0,  34,  59],
        [ 21, 100,  94]])

In [43]:
# Operações básicas com arrays

#soma dos elementos:
np.sum(vetor1)

#Produto dos elementos:
np.prod(vetor1)

#Soma acumulada:
np.cumsum(vetor1)

array([45, 46, 56, 59, 63])

In [47]:
#valores mínimo e máximo

#Valor Mínimo
#a.min()
print(np.min(vetor1))

#Valor Máximo
#a.max()
print(np.max(vetor1))


1
45


In [51]:
#Estatística básica
#o Numpy pega toda a população, enquanto o pandas calcula como se fosse uma amostra (na fórmula)

#Média
np.mean(minhamatriz)

#mediana
np.median(minhamatriz)

#desvio padrão
np.std(minhamatriz)

#variância
np.var(minhamatriz)

np.float64(1239.2098765432102)

In [59]:
#Desafio final
#Crie um array com 20 elementos (você pode escolher usar arange ou linspace)
#Calcule e imprima os seguintes valores estatísticos deste array:
#média, valor mínimo, desvio padrão, valor máximo, variância

arraynova = np.arange(20)
arraynova

print(np.var(arraynova))
print(np.mean(arraynova))
print(np.std(arraynova))
print(np.min(arraynova))
print(np.max(arraynova))



33.25
9.5
5.766281297335398
0
19
